[pytest]
filterwarnings =
    ignore:It is recommended to use web\.AppKey instances for keys\.:aiohttp.web_exceptions.NotAppKeyWarning
    ignore:Changing state of started or joined application is deprecated:DeprecationWarning
